name: Release

on:
  push:
    branches:
      - '**'

jobs:
  release:
    if: "contains(github.event.head_commit.message, 'chore: release')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build

      - name: Package Extension
        run: pnpm run zip

      - name: Get Version
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatgpt-exporter-v${{ steps.get_version.outputs.VERSION }}
          path: chatgpt-exporter.zip
          retention-days: 90

      - name: Publish to Chrome Web Store
        if: ${{ secrets.CHROME_EXTENSION_ID != '' && secrets.CHROME_CLIENT_ID != '' && secrets.CHROME_CLIENT_SECRET != '' && secrets.CHROME_REFRESH_TOKEN != '' }}
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: chatgpt-exporter.zip
          extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

      - name: Git commit
        id: commit
        run: |
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git config --local user.name github-actions[bot]
          git config --global core.autocrlf true
          git config --global core.safecrlf false
          git add .
          git commit -m "chore: ci build" -a
        continue-on-error: true

      - name: Git push
        uses: ad-m/github-push-action@master
        if: ${{ steps.commit.outcome == 'success' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Log
        if: ${{ steps.commit.outcome != 'success' }}
        run: echo Nothing to commit.
